sources:
  - name: GreenInvoice
    handler:
      jsonSchema:
        baseUrl: 'https://api.greeninvoice.co.il/api/v1'
        operationHeaders:
          Authorization: Bearer {env.GREEN_INVOICE_AUTH_TOKEN}
          Content-Type: application/json
        operations:
          - type: Mutation
            field: addExpenseByFile
            path: /expenses/file
            method: POST
            requestSchema: ./src/json-schemas/greenInvoice.json#/definitions/addExpenseByFileRequest
            responseSchema: ./src/json-schemas/greenInvoice.json#/definitions/addExpenseByFileResponse

          - type: Query
            field: getExpense
            path: /expenses/{args.id}
            method: GET
            requestSchema: ./src/json-schemas/greenInvoice.json#/definitions/getExpenseRequest
            responseSchema: ./src/json-schemas/greenInvoice.json#/definitions/getExpenseResponse


serve:
  browser: false

sdk:
  generateOperations:
    selectionSetDepth: 2

require:
  - ts-node/register/transpile-only
