sources:
  - name: Payper
    handler:
      jsonSchema:
        baseUrl: 'https://api.greeninvoice.co.il/api/v1'
        operationHeaders:
          API_KEY: '{env.GREEN_INVOICE_AUTH_TOKEN}'
          Content-Type: application/json
          Accept: application/json
        operations:
          - type: Query
            field: addExpenseByFile
            path: /expenses/file
            method: POST
            requestSchema: ./src/json-schemas/greenInvoice.json#/definitions/addExpenseByFileRequest
            responseSchema: ./src/json-schemas/greenInvoice.json#/definitions/addExpenseByFileResponse

serve:
  browser: false

sdk:
  generateOperations:
    selectionSetDepth: 2

require:
  - ts-node/register/transpile-only
